services:
  postgres:
    image: postgres:15-alpine
    container_name: livingston-postgres
    environment:
      POSTGRES_DB: livingston
      POSTGRES_USER: livingston
      POSTGRES_PASSWORD: livingston123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U livingston -d livingston"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: livingston-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@livingston.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
