ALTER TABLE "season_averages" ADD COLUMN "losses" integer;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "wins" integer;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "age" integer;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "pie" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "pace" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "possessions" integer;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "win_pct" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "ast_to" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "e_pace" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "fga_pg" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "fgm_pg" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "ts_pct" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "ast_pct" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "efg_pct" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "reb_pct" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "usg_pct" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "dreb_pct" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "oreb_pct" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "ast_ratio" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "e_tov_pct" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "e_usg_pct" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "def_rating" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "net_rating" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "off_rating" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "pace_per40" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "team_count" integer;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "tm_tov_pct" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "e_def_rating" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "e_net_rating" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "e_off_rating" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "sp_work_pace" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "sp_work_def_rating" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "sp_work_net_rating" real;--> statement-breakpoint
ALTER TABLE "season_averages" ADD COLUMN "sp_work_off_rating" real;