CREATE TABLE "clutch_season_averages" (
	"id" serial PRIMARY KEY NOT NULL,
	"player_id" integer NOT NULL,
	"season" integer NOT NULL,
	"games_played" integer,
	"minutes" real,
	"points" real,
	"assists" real,
	"rebounds" real,
	"steals" real,
	"blocks" real,
	"turnovers" real,
	"fgm" real,
	"fga" real,
	"fg_pct" real,
	"tpm" real,
	"tpa" real,
	"three_pct" real,
	"ftm" real,
	"fta" real,
	"ft_pct" real,
	"losses" integer,
	"wins" integer,
	"age" integer,
	"pie" real,
	"pace" real,
	"possessions" integer,
	"win_pct" real,
	"ast_to" real,
	"e_pace" real,
	"fga_pg" real,
	"fgm_pg" real,
	"ts_pct" real,
	"ast_pct" real,
	"efg_pct" real,
	"reb_pct" real,
	"usg_pct" real,
	"dreb_pct" real,
	"oreb_pct" real,
	"ast_ratio" real,
	"e_tov_pct" real,
	"e_usg_pct" real,
	"def_rating" real,
	"net_rating" real,
	"off_rating" real,
	"pace_per40" real,
	"team_count" integer,
	"tm_tov_pct" real,
	"e_def_rating" real,
	"e_net_rating" real,
	"e_off_rating" real,
	"sp_work_pace" real,
	"sp_work_def_rating" real,
	"sp_work_net_rating" real,
	"sp_work_off_rating" real,
	CONSTRAINT "clutch_season_averages_player_season_unique" UNIQUE("player_id","season")
);
--> statement-breakpoint
ALTER TABLE "clutch_season_averages" ADD CONSTRAINT "clutch_season_averages_player_id_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "clutch_season_averages_player_id_idx" ON "clutch_season_averages" USING btree ("player_id");--> statement-breakpoint
CREATE INDEX "clutch_season_averages_season_idx" ON "clutch_season_averages" USING btree ("season");